#!/bin/bash

echo "🔍 Verifica Evolution API sul VPS"
echo "================================"
echo ""
echo "Connettiti al VPS con:"
echo "ssh root@37.27.89.35"
echo ""
echo "Poi esegui questi comandi:"
echo ""
echo "# 1. Verifica se Evolution è attivo"
echo "docker ps | grep evolution"
echo ""
echo "# 2. Verifica i log"
echo "docker logs evolution_api --tail 50"
echo ""
echo "# 3. Verifica l'istanza assistenza"
echo "curl -X GET http://localhost:8080/instance/connectionState/assistenza \\"
echo "  -H 'apikey: 8C47777D-4EC9-4101-9246-5FFEAE763502'"
echo ""
echo "# 4. Lista tutte le istanze"
echo "curl -X GET http://localhost:8080/instance/fetchInstances \\"
echo "  -H 'apikey: 8C47777D-4EC9-4101-9246-5FFEAE763502'"
echo ""
echo "# 5. Se l'API key non funziona, prova a creare una nuova istanza:"
echo "curl -X POST http://localhost:8080/instance/create \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'apikey: IL_TUO_GLOBAL_API_KEY' \\"
echo "  -d '{\"instanceName\": \"assistenza\", \"integration\": \"BAILEYS\"}'"
