#!/bin/bash

echo "🔍 Verifica Funzionalità Professioni"
echo "===================================="
echo ""
echo "📋 Percorso per testare:"
echo "1. Menu laterale → 'Gestione Professionisti'"
echo "2. Clicca su 'Gestisci' su un professionista"
echo "3. Nella pagina che si apre, guarda le tab in alto"
echo "4. Clicca su 'Competenze'"
echo ""
echo "✅ Cosa dovresti vedere:"
echo "- Sezione 'Professione/Qualifica' con:"
echo "  - La professione attuale del professionista"
echo "  - Pulsante 'Modifica' per cambiarla"
echo "  - Dropdown con le 15 professioni disponibili"
echo ""
echo "📍 Dove gestire la tabella professioni:"
echo "- Menu laterale → 'Tabelle Sistema'"
echo "- Tab 'Professioni' per aggiungere/modificare/eliminare"
echo ""
echo "⚠️ Se non vedi la sezione professione:"
echo "1. Controlla che il backend sia riavviato"
echo "2. Apri console browser (F12) per eventuali errori"
echo "3. Ricarica la pagina con CTRL+F5"
